jobs:
  build:
    docker:
      - image: circleci/node

    steps:
      - checkout

      - run:
          name: npm-update
          command: 'sudo npm install -g npm@latest'

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: npm-install
          command: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run:
          name: test
          command: npm test